import { useEffect, useState } from "react";
import { Bell, X } from "lucide-react";
import { request } from "../../core/api";
import { subscribeRealtime } from "../../core/realtime";
import type { Appointment, PatientNotification, Tokens } from "../../core/types";
export default function PatientNotifications({ session }: { session: Tokens }) {
    const [items, setItems] = useState<PatientNotification[]>([]); const [proposals, setProposals] = useState<Appointment[]>([]); const [open, setOpen] = useState(false); const [busyId, setBusyId] = useState(""); const [message, setMessage] = useState("");
    async function load() { try { const [notifications, active] = await Promise.all([request<PatientNotification[]>("/appointments/notifications/mine", session.accessToken), request<Appointment[]>("/appointments/proposals/mine", session.accessToken)]); setItems(notifications); setProposals(active) } catch { /* Dashboard handles expired sessions. */ } }
    useEffect(() => { load(); const timer = window.setInterval(load, 15000); return () => window.clearInterval(timer) }, [session.accessToken]);
    useEffect(() => subscribeRealtime(() => { void load() }), [session.accessToken]);
    const unread = items.filter(x => !x.readAt);
    async function show() { setOpen(true); if (!unread.length) return; const readAt = new Date().toISOString(); setItems(current => current.map(x => !x.readAt ? { ...x, readAt } : x)); await Promise.all(unread.map(x => request(`/appointments/notifications/${x.id}/read`, session.accessToken, { method: "PATCH" }).catch(() => undefined))) }
    async function respond(id: string, action: "accept" | "decline") { setBusyId(id); setMessage(""); try { await request(`/appointments/proposals/${id}/${action}`, session.accessToken, { method: "POST" }); setMessage(action === "accept" ? "Đã xác nhận lịch khám với lễ tân." : "Đã từ chối và trả lại khung giờ."); await load(); window.dispatchEvent(new Event("appointments-changed")) } catch (x) { setMessage((x as Error).message) } finally { setBusyId("") } }
    const activeIds = new Set(proposals.map(x => x.id));
    return <><button className="notification-launcher" aria-label="Thông báo lịch khám" onClick={() => open ? setOpen(false) : show()}><Bell />{unread.length > 0 && <i>{unread.length > 9 ? "9+" : unread.length}</i>}</button>{open && <section className="notification-panel"><header><div><small>CẬP NHẬT LỊCH KHÁM</small><h3>Thông báo</h3></div><button aria-label="Đóng thông báo" onClick={() => setOpen(false)}><X /></button></header>{message && <p className="proposal-feedback">{message}</p>}<div className="notification-list">{items.length === 0 ? <div className="notification-empty"><span><Bell /></span><b>Chưa có thông báo mới</b><p>Các cập nhật về lịch khám sẽ xuất hiện tại đây.</p></div> : items.map(x => <article key={x.id} className={!x.readAt ? "unread" : ""}><b>{x.title}</b><p>{x.body}</p>{x.notificationType === "BOOKING_PROPOSAL" && x.appointmentId && (activeIds.has(x.appointmentId) ? <div className="proposal-actions"><button disabled={busyId === x.appointmentId} onClick={() => respond(x.appointmentId!, "accept")}>Đồng ý lịch này</button><button disabled={busyId === x.appointmentId} onClick={() => respond(x.appointmentId!, "decline")}>Từ chối</button></div> : <span className="proposal-resolved">Đề nghị đã được xử lý hoặc hết hạn</span>)}<small>{new Date(x.createdAt).toLocaleString("vi-VN")}</small></article>)}</div></section>}</>
}
