import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import { CalendarDays } from "lucide-react";
import { request } from "../../core/api";
import { subscribeRealtime } from "../../core/realtime";
import type { Appointment, AvailabilitySlot, Doctor, Patient } from "../../core/types";
import AppointmentList, { HideCancelledButton, ReviewControl } from "../../components/AppointmentList";
export default function PatientAppointments({ token, patient, appointments, changed }: { token: string; patient: Patient; appointments: Appointment[]; changed: (appointments: Appointment[]) => void }) {
    const [doctors, setDoctors] = useState<Doctor[]>([]); const [doctorId, setDoctorId] = useState(""); const [date, setDate] = useState(() => new Date().toISOString().slice(0, 10)); const [slots, setSlots] = useState<AvailabilitySlot[]>([]); const [selected, setSelected] = useState<AvailabilitySlot | null>(null); const [holdId, setHoldId] = useState(""); const [holdUntil, setHoldUntil] = useState(""); const [holdClock, setHoldClock] = useState(Date.now()); const [reason, setReason] = useState(""); const [items, setItems] = useState(appointments); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
    useEffect(() => { request<Doctor[]>("/doctors", token).then(list => { setDoctors(list); if (list[0]) setDoctorId(list[0].id) }).catch(x => setMessage((x as Error).message)) }, []);
    useEffect(()=>{const max=new Date();max.setDate(max.getDate()+60);document.querySelector<HTMLInputElement>(".patient-booking input[type=date]")?.setAttribute("max",max.toISOString().slice(0,10))},[]);
    useEffect(() => { setItems(appointments) }, [appointments]);
    const doctor = doctors.find(x => x.id === doctorId);
    async function findSlots(realtime = false) { if (!doctorId || !date) return; setBusy(true); if (!realtime) { setMessage(""); setSlots([]) } try { const result = await request<{ items: AvailabilitySlot[] }>(`/appointments/availability?doctorId=${encodeURIComponent(doctorId)}&date=${encodeURIComponent(date)}&durationMinutes=30`, token); setSlots(result.items); const own = result.items.find(x => x.status === "HELD_BY_YOU"); if (own) { setSelected(own); setHoldId(own.holdId || ""); setHoldUntil(own.holdExpiresAt || "") } else if (selected && !result.items.some(x => x.startAt === selected.startAt && x.status === "AVAILABLE")) { setSelected(null); setHoldId(""); setHoldUntil("") } const available = result.items.filter(x => x.status === "AVAILABLE").length; setMessage(result.items.length ? realtime ? "Lịch khám vừa được cập nhật tự động." : available ? "Chọn một khung giờ còn trống bên dưới." : "Các khung giờ trong ngày này đã kín." : "Bác sĩ chưa cấu hình lịch trong ngày đã chọn.") } catch (x) { setMessage((x as Error).message) } finally { setBusy(false) } }
    useEffect(() => { if (doctorId && date) findSlots() }, [doctorId, date]);
    useEffect(() => { if (!doctorId || !date) return; let live = true; const refresh = () => { if (live) findSlots(true) }; const unsubscribe = subscribeRealtime(refresh); const fallback = window.setInterval(refresh, 5000); window.addEventListener("focus", refresh); return () => { live = false; unsubscribe(); window.clearInterval(fallback); window.removeEventListener("focus", refresh) } }, [doctorId, date]);
    useEffect(() => { if (!holdUntil) return; const timer = window.setInterval(() => setHoldClock(Date.now()), 1000); const expiry = window.setTimeout(() => { releaseHold().then(() => findSlots(true)); setMessage("Thời gian giữ chỗ đã hết. Vui lòng chọn lại khung giờ.") }, Math.max(0, new Date(holdUntil).getTime() - Date.now()) + 250); return () => { window.clearInterval(timer); window.clearTimeout(expiry) } }, [holdUntil]);
    async function releaseHold() { if (!holdId) return; const id = holdId; setHoldId(""); setHoldUntil(""); setSelected(null); await request(`/appointments/holds/${id}`, token, { method: "DELETE" }).catch(() => undefined) }
    async function chooseSlot(slot: AvailabilitySlot) { if (busy) return; if (slot.status === "HELD_BY_YOU") { setBusy(true); try { await releaseHold(); setMessage("Đã nhả khung giờ. Người khác có thể đặt giờ này."); await findSlots(true) } finally { setBusy(false) } return } if (slot.status !== "AVAILABLE") return; setBusy(true); try { await releaseHold(); const held = await request<Appointment>("/appointments/holds", token, { method: "POST", body: JSON.stringify({ patientId: patient.id, doctorId: slot.doctorId, doctorIdentityId: slot.doctorIdentityId, startAt: slot.startAt, endAt: slot.endAt }) }); setSelected({ ...slot, status: "HELD_BY_YOU", holdId: held.id, holdExpiresAt: held.holdExpiresAt }); setHoldId(held.id); setHoldUntil(held.holdExpiresAt || ""); setMessage("Đã giữ khung giờ này cho bạn trong 5 phút.") } catch (x) { setMessage((x as Error).message); await findSlots(true) } finally { setBusy(false) } }
    async function book() { if (!selected || !holdId || !reason.trim()) return; setBusy(true); try { await request(`/appointments/holds/${holdId}/confirm`, token, { method: "POST", headers: { "Idempotency-Key": crypto.randomUUID() }, body: JSON.stringify({ reason: reason.trim() }) }); const latest = await request<Appointment[]>("/appointments/mine", token); setItems(latest); changed(latest); setReason(""); setSelected(null); setHoldId(""); setHoldUntil(""); setMessage("Đã gửi yêu cầu đặt lịch; lễ tân sẽ xác nhận với bạn."); await findSlots(true) } catch (x) { setMessage((x as Error).message); await findSlots(true) } finally { setBusy(false) } }
    async function cancel(id: string, cancelReason: string) { await request(`/appointments/${id}/cancel`, token, { method: "POST", body: JSON.stringify({ reason: cancelReason }) }); const latest = await request<Appointment[]>("/appointments/mine", token); setItems(latest); changed(latest) }
    const holdSeconds = holdUntil ? Math.max(0, Math.ceil((new Date(holdUntil).getTime() - holdClock) / 1000)) : 0;
    const holdCountdown = `${Math.floor(holdSeconds / 60)}:${String(holdSeconds % 60).padStart(2, "0")}`;
    return <div className="patient-booking"><section className="panel booking-shell">
        <aside className="doctor-choices"><h2>Chọn bác sĩ</h2>{doctors.map(d => <button key={d.id} className={doctorId === d.id ? "selected" : ""} onClick={() => { setDoctorId(d.id); void releaseHold() }}>{d.avatarUrl ? <img src={d.avatarUrl} alt={d.fullName} /> : <span>{d.fullName.slice(0, 1).toUpperCase()}</span>}<div><b>BS. {d.fullName}</b><small>{d.specialtyCode}</small><em>{d.experienceYears} năm kinh nghiệm</em></div></button>)}</aside>
        <div className="booking-main">{doctor && <div className="selected-doctor"><div className="selected-doctor-photo">{doctor.avatarUrl ? <img src={doctor.avatarUrl} alt={doctor.fullName} /> : <span>{doctor.fullName.slice(0, 1).toUpperCase()}</span>}</div><div><small>BÁC SĨ PHỤ TRÁCH</small><h2>BS. {doctor.fullName}</h2><p>{doctor.specialtyCode} · {doctor.experienceYears} năm kinh nghiệm</p>{doctor.certificateNo && <em>Chứng chỉ: {doctor.certificateNo}</em>}{doctor.bio && <p className="selected-doctor-bio">{doctor.bio}</p>}</div></div>}
            <div className="date-slot-head"><label>Ngày muốn khám<input type="date" min={new Date().toISOString().slice(0, 10)} value={date} onChange={e => { setDate(e.target.value); void releaseHold() }} /></label><div><b>Khung giờ khám</b><small>30 phút/lượt · Màu vàng là slot đang được giữ tạm</small></div></div>
            <div className="slot-grid">{busy && slots.length === 0 ? <p>Đang kiểm tra lịch bác sĩ…</p> : slots.map(slot => { const unavailable = !["AVAILABLE", "HELD_BY_YOU"].includes(slot.status); const statusClass = slot.status.toLowerCase().replaceAll("_", "-"); return <button key={slot.startAt} disabled={unavailable} className={`${selected?.startAt === slot.startAt ? "selected" : ""} ${unavailable ? "unavailable" : ""} ${statusClass}`} onClick={() => chooseSlot(slot)}><b>{new Date(slot.startAt).toLocaleTimeString("vi-VN", { hour: "2-digit", minute: "2-digit" })}</b><small>{slot.status === "BOOKED" ? "Đã đặt" : slot.status === "ON_LEAVE" ? "Bác sĩ nghỉ" : slot.status === "HELD_BY_YOU" ? `Đang giữ · ${holdCountdown}` : slot.status === "HELD_BY_OTHER" ? "Đang có người chọn" : "Còn trống"}</small></button> })}</div>
            <label className="booking-reason">Mô tả triệu chứng hoặc nhu cầu thăm khám<textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Ví dụ: nổi mẩn đỏ, ngứa da trong 3 ngày…" /></label>
            {selected && <><div className="booking-summary"><CalendarDays /><div><b>{new Date(selected.startAt).toLocaleString("vi-VN")}</b><small>với BS. {selected.doctorName}</small></div><button disabled={busy || !reason.trim() || !holdId} onClick={book}>{busy ? "Đang gửi…" : "Xác nhận đặt lịch"}</button></div>{holdUntil && <p className="hold-note">Đang giữ riêng cho bạn: <b>{holdCountdown}</b>. Nhấn lại khung giờ để nhả chỗ.</p>}</>}
            {message && <p className="booking-message">{message}</p>}
        </div></section><AppointmentList token={token} appointments={items} cancel={cancel} patientName={patient.fullName} /></div>
}
