package com.dermai.prescription;

import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.*;
import org.springframework.web.server.ResponseStatusException;

@Service @Transactional
public class BillingService {
 private static final BigDecimal ZERO=BigDecimal.ZERO;
 private final InvoiceRepository invoices;private final InvoiceCashPaymentRepository cashPayments;private final InventoryMovementRepository movements;private final InvoiceAdjustmentRepository adjustments;private final MedicineRepository medicines;private final PrescriptionRepository prescriptions;private final RestClient appointments;private final RestClient payments;private final String serviceToken;private final Clock clock;private final BillingReceptionEvents receptionEvents;
 BillingService(InvoiceRepository invoices,InvoiceCashPaymentRepository cashPayments,InventoryMovementRepository movements,InvoiceAdjustmentRepository adjustments,MedicineRepository medicines,PrescriptionRepository prescriptions,@Value("${services.appointment-url}")String appointmentUrl,@Value("${services.payment-url}")String paymentUrl,@Value("${services.token:}")String serviceToken,Clock clock,BillingReceptionEvents receptionEvents){this.invoices=invoices;this.cashPayments=cashPayments;this.movements=movements;this.adjustments=adjustments;this.medicines=medicines;this.prescriptions=prescriptions;this.appointments=RestClient.builder().baseUrl(appointmentUrl).build();this.payments=RestClient.builder().baseUrl(paymentUrl).build();this.serviceToken=serviceToken;this.clock=clock;this.receptionEvents=receptionEvents;}
 public Invoice create(UUID appointmentId,UUID prescriptionId,boolean buyMedicines,UUID actor){
  var old=invoices.findByAppointmentId(appointmentId);if(old.isPresent())return syncDeposit(old.get(),actor);
  var appointment=appointments.get().uri("/api/v1/appointments/{id}",appointmentId).header("X-User-Id",actor.toString()).header("X-User-Role","RECEPTIONIST").retrieve().body(AppointmentView.class);
  if(appointment==null||!Set.of("COMPLETED","FOLLOW_UP_REQUIRED").contains(appointment.status()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Chỉ lập hóa đơn sau khi hoàn tất khám");
  var fee=nonNegative(appointment.consultationFeeSnapshot());var invoice=new Invoice();invoice.id=UUID.randomUUID();invoice.appointmentId=appointmentId;invoice.patientId=appointment.patientId();invoice.patientIdentityId=appointment.patientIdentityId();invoice.consultationFee=fee;invoice.serviceFee=ZERO;invoice.prescriptionId=prescriptionId;invoice.createdBy=actor;invoice.createdAt=clock.instant();invoice.depositApplied=successfulDeposit(appointmentId,actor);if(invoice.depositApplied.signum()==0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Lượt khám chưa có tiền cọc thành công");
  var confirmedServices=appointments.get().uri("/api/v1/appointments/{id}/performed-services",appointmentId).header("X-User-Id",actor.toString()).header("X-User-Role","RECEPTIONIST").retrieve().body(PerformedServicesView.class);
  if(confirmedServices==null||confirmedServices.confirmedAt()==null)throw new ResponseStatusException(HttpStatus.CONFLICT,"Bác sĩ chưa xác nhận dịch vụ đã thực hiện cho ca khám này");
  for(var service:Optional.ofNullable(confirmedServices.items()).orElseGet(List::of)){var item=new Invoice.ServiceItem();item.serviceId=service.serviceId();item.serviceCode=service.serviceCode();item.serviceName=service.serviceName();item.unitPrice=nonNegative(service.unitPrice());invoice.serviceItems.add(item);}
  invoice.serviceFee=invoice.serviceItems.stream().map(i->i.unitPrice).reduce(ZERO,BigDecimal::add);
  Prescription prescription=null;
  if(prescriptionId!=null){
   prescription=prescriptions.findById(prescriptionId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Không tìm thấy đơn thuốc"));
   if(!appointmentId.equals(prescription.appointmentId)||!appointment.patientId().equals(prescription.patientId))throw new ResponseStatusException(HttpStatus.CONFLICT,"Đơn thuốc không thuộc lượt khám này");
  }
  if(buyMedicines){
   if(prescription==null)throw new ResponseStatusException(HttpStatus.CONFLICT,"Chưa có đơn thuốc để bán tại phòng khám");
   invoice.medicineFulfillment=Invoice.MedicineFulfillment.CLINIC_PHARMACY;
   for(var prescribed:prescription.items){var medicine=medicines.findById(prescribed.medicineId).filter(m->m.active).orElseThrow(()->new ResponseStatusException(HttpStatus.CONFLICT,"Thuốc không còn trong danh mục kê đơn: "+prescribed.drugName));if(!medicines.isClinicSaleActive(medicine.id))throw new ResponseStatusException(HttpStatus.CONFLICT,"Thuốc "+medicine.name+" hiện không bán tại phòng khám. Vui lòng chọn bệnh nhân tự mua thuốc ngoài.");var item=new Invoice.Item();item.medicineId=medicine.id;item.medicineName=medicine.name;item.unit=medicine.unit;item.unitPrice=medicine.salePrice;item.prescribedQuantity=prescribed.quantityRequested;item.dispensedQuantity=0;item.lineTotal=medicine.salePrice.multiply(BigDecimal.valueOf(item.prescribedQuantity));invoice.items.add(item);}
  }else invoice.medicineFulfillment=prescription==null?Invoice.MedicineFulfillment.NO_PRESCRIPTION:Invoice.MedicineFulfillment.OUTSIDE_PHARMACY;
  invoice.medicineTotal=invoice.items.stream().map(i->i.lineTotal).reduce(ZERO,BigDecimal::add);invoice.totalAmount=fee.add(invoice.serviceFee).add(invoice.medicineTotal);invoice.depositApplied=invoice.depositApplied.min(invoice.totalAmount);invoice.remainingAmount=invoice.totalAmount.subtract(invoice.depositApplied);invoice.status=invoice.remainingAmount.signum()==0?Invoice.Status.PAID:Invoice.Status.AWAITING_PAYMENT;if(invoice.status==Invoice.Status.PAID)invoice.paidAt=clock.instant();var saved=invoices.save(invoice);receptionEvents.created(saved);if(saved.status==Invoice.Status.PAID)receptionEvents.paid(saved);return saved;
 }
 @Transactional(readOnly=true) public Invoice get(UUID id,UUID actor,String role){var invoice=invoices.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));if("PATIENT".equals(role)&&!actor.equals(invoice.patientIdentityId))throw new ResponseStatusException(HttpStatus.FORBIDDEN);if(!Set.of("PATIENT","RECEPTIONIST","ADMIN").contains(role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);return invoice;}
 @Transactional(readOnly=true) public List<Invoice> list(UUID actor,String role){if("PATIENT".equals(role))return invoices.findByPatientIdentityIdOrderByCreatedAtDesc(actor);if(Set.of("RECEPTIONIST","ADMIN").contains(role))return invoices.findTop100ByOrderByCreatedAtDesc();throw new ResponseStatusException(HttpStatus.FORBIDDEN);}
 public Invoice refreshDeposit(UUID id,UUID actor,String role){return syncDeposit(get(id,actor,role),actor);}
 public Receipt collectCash(UUID id,BigDecimal received,String station,UUID actor){var invoice=syncDeposit(get(id,actor,"RECEPTIONIST"),actor);if(invoice.status!=Invoice.Status.AWAITING_PAYMENT)throw new ResponseStatusException(HttpStatus.CONFLICT,"Hóa đơn đã được thanh toán đủ bằng tiền cọc");if(cashPayments.findByInvoiceId(id).isPresent())throw new ResponseStatusException(HttpStatus.CONFLICT,"Giao dịch tiền mặt đã tồn tại và không thể sửa");if(received.compareTo(invoice.remainingAmount)<0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Số tiền khách đưa chưa đủ");var cash=new InvoiceCashPayment();cash.id=UUID.randomUUID();cash.invoiceId=id;cash.amountDue=invoice.remainingAmount;cash.amountReceived=received;cash.changeAmount=received.subtract(invoice.remainingAmount);cash.collectedBy=actor;cash.collectedAt=clock.instant();cash.cashierStation=station.trim();cashPayments.save(cash);var paid=markPaid(invoice,cash.collectedAt);receptionEvents.paid(paid);return new Receipt(paid,cash);}
 public Object createOnlinePayment(UUID id,UUID actor,String role){var invoice=syncDeposit(get(id,actor,role),actor);if(invoice.status!=Invoice.Status.AWAITING_PAYMENT)throw new ResponseStatusException(HttpStatus.CONFLICT,"Hóa đơn đã được thanh toán đủ bằng tiền cọc");return payments.post().uri("/api/v1/payments/internal/invoices").header("X-Service-Token",serviceToken).body(Map.of("invoiceId",invoice.id,"patientIdentityId",invoice.patientIdentityId,"amount",invoice.remainingAmount)).retrieve().body(Object.class);}
 public void markOnlinePaid(UUID invoiceId,BigDecimal amount){var invoice=invoices.findById(invoiceId).orElse(null);if(invoice==null||invoice.status==Invoice.Status.PAID||invoice.status==Invoice.Status.DISPENSED)return;if(amount.compareTo(invoice.remainingAmount)!=0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Số tiền hóa đơn không khớp");receptionEvents.paid(markPaid(invoice,clock.instant()));}
 public Invoice dispense(UUID id,UUID actor){var invoice=get(id,actor,"RECEPTIONIST");if(invoice.status==Invoice.Status.DISPENSED)return invoice;if(invoice.status!=Invoice.Status.PAID)throw new ResponseStatusException(HttpStatus.CONFLICT,"Chỉ giao thuốc khi hóa đơn đã thanh toán");if(invoice.medicineFulfillment!=Invoice.MedicineFulfillment.CLINIC_PHARMACY||invoice.items.isEmpty())throw new ResponseStatusException(HttpStatus.CONFLICT,"Hóa đơn này không nhận thuốc tại phòng khám");if(movements.existsByInvoiceId(id))throw new ResponseStatusException(HttpStatus.CONFLICT,"Kho đã được trừ cho hóa đơn này");for(var item:invoice.items){var medicine=medicines.findLockedById(item.medicineId).orElseThrow();if(medicine.stockQuantity<item.prescribedQuantity)throw new ResponseStatusException(HttpStatus.CONFLICT,"Không đủ tồn kho: "+medicine.name);medicine.stockQuantity-=item.prescribedQuantity;medicine.updatedAt=clock.instant();item.dispensedQuantity=item.prescribedQuantity;var movement=new InventoryMovement();movement.id=UUID.randomUUID();movement.invoiceId=invoice.id;movement.medicineId=medicine.id;movement.quantityDelta=-item.prescribedQuantity;movement.performedBy=actor;movement.createdAt=clock.instant();movement.reason="DISPENSED";movements.save(movement);}invoice.status=Invoice.Status.DISPENSED;invoice.dispensedAt=clock.instant();invoice.dispensedBy=actor;return invoices.save(invoice);}
 public InvoiceAdjustment adjust(UUID id,BigDecimal delta,String reason,UUID actor){get(id,actor,"ADMIN");var adjustment=new InvoiceAdjustment();adjustment.id=UUID.randomUUID();adjustment.invoiceId=id;adjustment.amountDelta=delta;adjustment.reason=reason.trim();adjustment.createdBy=actor;adjustment.createdAt=clock.instant();return adjustments.save(adjustment);}
 @Transactional(readOnly=true) public Summary summary(Instant from,Instant to){var recognized=invoices.findByPaidAtBetweenOrderByPaidAtDesc(from,to).stream().filter(i->Set.of(Invoice.Status.PAID,Invoice.Status.DISPENSED).contains(i.status)).toList();var created=invoices.findByCreatedAtBetweenOrderByCreatedAtDesc(from,to);var cash=sumCash(recognized);var deposits=sum(recognized,i->i.depositApplied);var invoiceOnline=sum(recognized,i->i.totalAmount).subtract(cash).subtract(deposits).max(ZERO);return new Summary(deposits,sum(recognized,i->i.consultationFee),sum(recognized,i->i.serviceFee),sum(recognized,i->i.medicineTotal),invoiceOnline,cash,recognized.size(),created.stream().filter(i->i.status==Invoice.Status.AWAITING_PAYMENT).count());}
 @Transactional(readOnly=true) public List<DailyCashFlow> cashFlow(Instant from,Instant to){var buckets=new TreeMap<LocalDate,BigDecimal[]>();for(var invoice:invoices.findByPaidAtBetweenOrderByPaidAtDesc(from,to)){if(!Set.of(Invoice.Status.PAID,Invoice.Status.DISPENSED).contains(invoice.status)||invoice.paidAt==null)continue;var cash=cashPayments.findByInvoiceId(invoice.id).map(item->item.amountDue).orElse(ZERO);var online=invoice.totalAmount.subtract(invoice.depositApplied).subtract(cash).max(ZERO);var day=LocalDate.ofInstant(invoice.paidAt,ZoneId.of("Asia/Ho_Chi_Minh"));var values=buckets.computeIfAbsent(day,key->new BigDecimal[]{ZERO,ZERO,ZERO,ZERO,ZERO});values[0]=values[0].add(online);values[1]=values[1].add(cash);values[2]=values[2].add(invoice.consultationFee);values[3]=values[3].add(invoice.serviceFee);values[4]=values[4].add(invoice.medicineTotal);}return buckets.entrySet().stream().map(entry->new DailyCashFlow(entry.getKey(),entry.getValue()[0],entry.getValue()[1],entry.getValue()[2],entry.getValue()[3],entry.getValue()[4])).toList();}
 private BigDecimal successfulDeposit(UUID appointmentId,UUID actor){try{var value=payments.get().uri("/api/v1/payments/booking/{id}",appointmentId).header("X-User-Id",actor.toString()).header("X-User-Role","RECEPTIONIST").retrieve().body(DepositView.class);return value!=null&&"SUCCESS".equals(value.status())?nonNegative(value.amount()):ZERO;}catch(HttpClientErrorException.NotFound missing){return ZERO;}}
 private Invoice syncDeposit(Invoice invoice,UUID actor){if(invoice.status!=Invoice.Status.AWAITING_PAYMENT)return invoice;var deposit=successfulDeposit(invoice.appointmentId,actor).min(invoice.totalAmount);if(deposit.compareTo(invoice.depositApplied)<=0)return invoice;invoice.depositApplied=deposit;invoice.remainingAmount=invoice.totalAmount.subtract(deposit);if(invoice.remainingAmount.signum()==0){invoice.status=Invoice.Status.PAID;invoice.paidAt=clock.instant();}var saved=invoices.save(invoice);if(saved.status==Invoice.Status.PAID)receptionEvents.paid(saved);return saved;}
 private Invoice markPaid(Invoice invoice,Instant paidAt){invoice.status=Invoice.Status.PAID;invoice.paidAt=paidAt;invoice.remainingAmount=ZERO;return invoices.save(invoice);}
 private BigDecimal nonNegative(BigDecimal value){return value==null||value.signum()<0?ZERO:value;}
 private BigDecimal sum(List<Invoice> data,java.util.function.Function<Invoice,BigDecimal> field){return data.stream().map(field).reduce(ZERO,BigDecimal::add);}private BigDecimal sumCash(List<Invoice> data){return data.stream().map(i->cashPayments.findByInvoiceId(i.id).map(c->c.amountDue).orElse(ZERO)).reduce(ZERO,BigDecimal::add);}
 record AppointmentView(UUID id,UUID patientId,UUID patientIdentityId,BigDecimal consultationFeeSnapshot,String status){}record PerformedServicesView(UUID appointmentId,Instant confirmedAt,List<PerformedServiceItem> items){}record PerformedServiceItem(UUID serviceId,String serviceCode,String serviceName,BigDecimal unitPrice){}record DepositView(BigDecimal amount,String status){}
 public record Receipt(Invoice invoice,InvoiceCashPayment cashPayment){}
 public record Summary(BigDecimal deposits,BigDecimal consultationFees,BigDecimal serviceFees,BigDecimal medicineRevenue,BigDecimal onlineReceived,BigDecimal cashReceived,long paidInvoices,long awaitingInvoices){}
 public record DailyCashFlow(LocalDate date,BigDecimal onlineReceived,BigDecimal cashReceived,BigDecimal consultationFees,BigDecimal serviceFees,BigDecimal medicineRevenue){}
}
