package com.dermai.appointment;
import org.junit.jupiter.api.Test;import java.time.*;import java.util.*;import static org.assertj.core.api.Assertions.*;
class SchedulingEngineTest{
 @Test void filtersAndRanks(){var t=Instant.parse("2027-01-01T01:00:00Z");var good=new SchedulingEngine.Candidate(UUID.randomUUID(),t,t.plusSeconds(1800),1,.8,.3,1,.5,true,false,false);var conflict=new SchedulingEngine.Candidate(UUID.randomUUID(),t,t.plusSeconds(1800),1,1,1,1,1,true,false,true);var out=new SchedulingEngine().recommend(List.of(conflict,good),5);assertThat(out).hasSize(1);assertThat(out.getFirst().score()).isEqualTo(.785);}
 @Test void stateMachineRejectsInvalid(){assertThat(AppointmentStatus.CONFIRMED.mayTransitionTo(AppointmentStatus.IN_PROGRESS)).isTrue();assertThat(AppointmentStatus.COMPLETED.mayTransitionTo(AppointmentStatus.CANCELLED)).isFalse();}
 @Test void heldSlotCanOnlyBeConfirmedOrReleased(){assertThat(AppointmentStatus.HELD.mayTransitionTo(AppointmentStatus.ASSIGNED)).isTrue();assertThat(AppointmentStatus.HELD.mayTransitionTo(AppointmentStatus.CANCELLED)).isTrue();assertThat(AppointmentStatus.HELD.mayTransitionTo(AppointmentStatus.CONFIRMED)).isFalse();}
 @Test void confirmedVisitCanBecomeNoShow(){assertThat(AppointmentStatus.CONFIRMED.mayTransitionTo(AppointmentStatus.NO_SHOW)).isTrue();assertThat(AppointmentStatus.ASSIGNED.mayTransitionTo(AppointmentStatus.NO_SHOW)).isFalse();}
 @Test void checkedInVisitCanStartButCannotBecomeNoShow(){assertThat(AppointmentStatus.CHECKED_IN.mayTransitionTo(AppointmentStatus.IN_PROGRESS)).isTrue();assertThat(AppointmentStatus.CHECKED_IN.mayTransitionTo(AppointmentStatus.NO_SHOW)).isFalse();}
 @Test void patientCanAcceptOrDeclineReceptionistProposal(){assertThat(AppointmentStatus.PROPOSED.mayTransitionTo(AppointmentStatus.CONFIRMED)).isTrue();assertThat(AppointmentStatus.PROPOSED.mayTransitionTo(AppointmentStatus.CANCELLED)).isTrue();assertThat(AppointmentStatus.PROPOSED.mayTransitionTo(AppointmentStatus.IN_PROGRESS)).isFalse();}
 @Test void cancelledSlotCannotReturnToAnActiveState(){for(var target:List.of(AppointmentStatus.HELD,AppointmentStatus.PENDING,AppointmentStatus.ASSIGNED,AppointmentStatus.CONFIRMED,AppointmentStatus.IN_PROGRESS))assertThat(AppointmentStatus.CANCELLED.mayTransitionTo(target)).isFalse();}
 @Test void completedAppointmentCannotBeRescheduledOrRestarted(){assertThat(AppointmentStatus.COMPLETED.mayTransitionTo(AppointmentStatus.ASSIGNED)).isFalse();assertThat(AppointmentStatus.COMPLETED.mayTransitionTo(AppointmentStatus.IN_PROGRESS)).isFalse();}
}
