package com.dermai.appointment;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/appointments")
public class AppointmentController{
 private final AppointmentService service;private final AppointmentRepository repo;private final SchedulingRecommendationService recommendations;private final AppointmentActionAuditService audit;
 AppointmentController(AppointmentService s,AppointmentRepository r,SchedulingRecommendationService recommendations,AppointmentActionAuditService audit){service=s;repo=r;this.recommendations=recommendations;this.audit=audit;}
 record Book(@NotNull UUID patientId,UUID patientIdentityId,UUID doctorId,UUID doctorIdentityId,@NotNull Instant startAt,@NotNull Instant endAt,@NotBlank @Size(max=500) String reason){}
 record Assign(@NotNull UUID doctorId,@NotNull UUID doctorIdentityId,Instant startAt,Instant endAt){}record Cancel(@NotBlank @Size(max=500) String reason){}record Move(@NotNull Instant startAt,@NotNull Instant endAt){}record RequireFollowUp(@NotBlank @Size(max=500) String reason,@NotNull Instant notBefore){}
 @PostMapping ResponseEntity<Appointment> book(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role,@RequestHeader(value="Authorization",required=false) String authorization,@RequestHeader(value="Idempotency-Key",required=false) String key,@Valid @RequestBody Book b){requireAny(role,"PATIENT","RECEPTIONIST","ADMIN");UUID owner=role.equals("PATIENT")?user:Objects.requireNonNull(b.patientIdentityId(),"patientIdentityId bắt buộc khi nhân viên đặt lịch");var fee=recommendations.assertAvailable(b.doctorId(),b.startAt(),b.endAt(),null,authorization,role);var appointment=service.book(b.patientId(),owner,b.doctorId(),b.doctorIdentityId(),b.startAt(),b.endAt(),b.reason(),fee,key,!role.equals("PATIENT"));audit.record(appointment.id,user,role,"BOOKED_FOR_PATIENT");return ResponseEntity.status(201).body(appointment);}
 @GetMapping("/mine") List<Appointment> mine(@RequestHeader("X-User-Id") UUID user){return repo.findByPatientIdentityIdOrderByStartAtDesc(user).stream().filter(x->!x.patientHidden&&x.status!=AppointmentStatus.HELD).toList();}
 @GetMapping("/{id}") Appointment get(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){
  var x=repo.findById(id).orElseThrow(NoSuchElementException::new);
  boolean allowed=Set.of("ADMIN","RECEPTIONIST").contains(role)||("PATIENT".equals(role)&&identity.equals(x.patientIdentityId))||("DOCTOR".equals(role)&&identity.equals(x.doctorIdentityId));
  if(!allowed)throw new Forbidden();return x;
 }
 @GetMapping("/doctor/{id}") List<Appointment> doctor(@PathVariable UUID id,@RequestParam Instant from,@RequestParam Instant to,@RequestHeader("X-User-Role") String role){requireAny(role,"DOCTOR","RECEPTIONIST","ADMIN");return repo.findByDoctorIdAndStartAtBetweenOrderByStartAt(id,from,to);}
 @GetMapping("/doctor/mine") List<Appointment> doctorMine(@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role,@RequestParam Instant from,@RequestParam Instant to){requireAny(role,"DOCTOR");return repo.findByDoctorIdentityIdAndStartAtBetweenOrderByStartAt(identity,from,to).stream().filter(x->EnumSet.of(AppointmentStatus.CONFIRMED,AppointmentStatus.CHECKED_IN,AppointmentStatus.IN_PROGRESS,AppointmentStatus.COMPLETED,AppointmentStatus.FOLLOW_UP_REQUIRED).contains(x.status)).toList();}
 @GetMapping("/queue") List<Appointment> queue(@RequestHeader("X-User-Role") String role,@RequestParam Instant from,@RequestParam Instant to,@RequestParam(required=false) Set<AppointmentStatus> status){requireAny(role,"RECEPTIONIST","ADMIN");var states=status==null||status.isEmpty()?EnumSet.allOf(AppointmentStatus.class):status;states.remove(AppointmentStatus.HELD);return repo.findByStatusInAndStartAtBetweenOrderByStartAt(states,from,to);}
 @GetMapping("/staff-actions") List<AppointmentActionLog> staffActions(@RequestHeader("X-User-Role") String role,@RequestParam UUID actorIdentityId){requireAny(role,"ADMIN");return audit.recentFor(actorIdentityId);}
 @PostMapping("/recommendations") Object recommend(@RequestHeader(value="Authorization",required=false) String authorization,@RequestHeader("X-User-Role") String role,@Valid @RequestBody SchedulingRecommendationService.Request r){requireAny(role,"PATIENT","RECEPTIONIST","DOCTOR","ADMIN");return recommendations.recommend(r,authorization,role);}
 @GetMapping("/availability") Object availability(@RequestParam UUID doctorId,@RequestParam LocalDate date,@RequestParam(defaultValue="30") int durationMinutes,@RequestHeader("X-User-Id") UUID identity,@RequestHeader(value="Authorization",required=false) String authorization,@RequestHeader("X-User-Role") String role){requireAny(role,"PATIENT","RECEPTIONIST","DOCTOR","ADMIN");return recommendations.availability(doctorId,date,durationMinutes,identity,authorization,role);}
 @PostMapping("/{id}/assign") Appointment assign(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role,@RequestHeader(value="Authorization",required=false) String authorization,@Valid @RequestBody Assign x){requireAny(role,"RECEPTIONIST","ADMIN");var old=repo.findById(id).orElseThrow(NoSuchElementException::new);var fee=recommendations.assertAvailable(x.doctorId(),x.startAt()==null?old.startAt:x.startAt(),x.endAt()==null?old.endAt:x.endAt(),id,authorization,role);var appointment=service.assign(id,x.doctorId(),x.doctorIdentityId(),x.startAt(),x.endAt(),fee);audit.record(appointment.id,identity,role,"ASSIGNED_DOCTOR");return appointment;}
 @PostMapping("/{id}/confirm") Appointment confirm(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){requireAny(role,"RECEPTIONIST","ADMIN");var appointment=service.transition(id,AppointmentStatus.CONFIRMED);audit.record(appointment.id,identity,role,"CONFIRMED");return appointment;}
 @PostMapping("/{id}/check-in") Appointment checkIn(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){requireAny(role,"RECEPTIONIST","ADMIN");var appointment=service.checkIn(id);audit.record(appointment.id,identity,role,"CHECKED_IN");return appointment;}
 @PostMapping("/{id}/start") Appointment start(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){requireAny(role,"DOCTOR");requireDoctorOwner(id,identity);return service.transition(id,AppointmentStatus.IN_PROGRESS);}
 @PostMapping("/{id}/complete") Appointment complete(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){
  requireAny(role,"DOCTOR","RECEPTIONIST","ADMIN");
  Appointment appointment;
  if("DOCTOR".equals(role)){requireDoctorOwner(id,identity);appointment=service.transition(id,AppointmentStatus.COMPLETED);}
  else appointment=service.completeStaleConsultation(id);
  audit.record(appointment.id,identity,role,"COMPLETED_VISIT");return appointment;
 }
 @PostMapping("/{id}/no-show") Appointment noShow(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){requireAny(role,"RECEPTIONIST","ADMIN");var appointment=service.noShow(id);audit.record(appointment.id,identity,role,"NO_SHOW");return appointment;}
 @PostMapping("/{id}/cancel") Appointment cancel(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role,@Valid @RequestBody Cancel x){requireAny(role,"PATIENT","RECEPTIONIST","ADMIN");if("PATIENT".equals(role))requirePatientSelfServiceWindow(id,identity);var appointment=service.cancel(id,x.reason());audit.record(appointment.id,identity,role,"CANCELLED");return appointment;}
 @PatchMapping("/{id}/hide") ResponseEntity<Void> hideCancelled(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){requireAny(role,"PATIENT");var appointment=repo.findById(id).orElseThrow(NoSuchElementException::new);if(!identity.equals(appointment.patientIdentityId))throw new Forbidden();if(appointment.status!=AppointmentStatus.CANCELLED)throw new ResponseStatusException(HttpStatus.CONFLICT,"Chỉ có thể ẩn lịch đã hủy.");appointment.patientHidden=true;repo.save(appointment);return ResponseEntity.noContent().build();}
 @PostMapping("/{id}/reschedule") Appointment move(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role,@RequestHeader(value="Authorization",required=false) String authorization,@RequestHeader(value="Idempotency-Key",required=false) String key,@Valid @RequestBody Move x){requireAny(role,"PATIENT","RECEPTIONIST","ADMIN");var old="PATIENT".equals(role)?requirePatientSelfServiceWindow(id,identity):repo.findById(id).orElseThrow(NoSuchElementException::new);recommendations.assertAvailable(old.doctorId,x.startAt(),x.endAt(),id,authorization,role);var appointment=service.reschedule(id,x.startAt(),x.endAt(),key,!role.equals("PATIENT"));audit.record(id,identity,role,"RESCHEDULED");return appointment;}
 @PostMapping("/{id}/require-follow-up") Appointment requireFollowUp(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role,@Valid @RequestBody RequireFollowUp x){requireAny(role,"DOCTOR");requireDoctorOwner(id,identity);return service.requireFollowUp(id,x.reason(),x.notBefore());}
 @PostMapping("/{id}/follow-up") Appointment follow(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role,@RequestHeader(value="Authorization",required=false) String authorization,@RequestHeader(value="Idempotency-Key",required=false) String key,@Valid @RequestBody Move x){requireAny(role,"PATIENT","RECEPTIONIST","ADMIN");if("PATIENT".equals(role))requirePatientOwner(id,identity);var old=repo.findById(id).orElseThrow(NoSuchElementException::new);var fee=recommendations.assertAvailable(old.doctorId,x.startAt(),x.endAt(),id,authorization,role);return service.followUp(id,x.startAt(),x.endAt(),fee,key,!role.equals("PATIENT"));}
 private void requireAny(String got,String...roles){if(Arrays.stream(roles).noneMatch(got::equals))throw new Forbidden();}
 private void requireDoctorOwner(UUID id,UUID identity){if(repo.findById(id).map(x->!identity.equals(x.doctorIdentityId)).orElse(true))throw new Forbidden();}
 private void requirePatientOwner(UUID id,UUID identity){if(repo.findById(id).map(x->!identity.equals(x.patientIdentityId)).orElse(true))throw new Forbidden();}
 // Patients may self-manage for 30 minutes only before reception confirms the appointment.
 private Appointment requirePatientSelfServiceWindow(UUID id,UUID identity){var appointment=repo.findById(id).orElseThrow(NoSuchElementException::new);if(!identity.equals(appointment.patientIdentityId))throw new Forbidden();if(appointment.status==AppointmentStatus.CONFIRMED)throw new ResponseStatusException(HttpStatus.CONFLICT,"Lịch đã được lễ tân xác nhận. Vui lòng liên hệ hỗ trợ để đổi hoặc hủy lịch.");if(!EnumSet.of(AppointmentStatus.PENDING,AppointmentStatus.ASSIGNED).contains(appointment.status))throw new ResponseStatusException(HttpStatus.CONFLICT,"Trạng thái lịch hiện tại không cho phép tự đổi hoặc hủy.");if(appointment.createdAt.plus(Duration.ofMinutes(30)).isBefore(Instant.now()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Quá 30 phút kể từ lúc đặt lịch. Vui lòng liên hệ lễ tân để được hỗ trợ đổi hoặc hủy lịch.");return appointment;}
 @ResponseStatus(HttpStatus.FORBIDDEN) static class Forbidden extends RuntimeException{}
}
