package com.dermai.appointment;
import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.util.NoSuchElementException;
@RestControllerAdvice class AppointmentErrors{
 @ExceptionHandler(BookingPolicy.ActiveAppointmentLimitException.class) ResponseEntity<ProblemDetail> activeLimit(){var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Bạn đã có tối đa 3 lịch khám sắp tới. Vui lòng hoàn thành hoặc hủy một lịch trước khi đặt thêm.");p.setProperty("code","ACTIVE_APPOINTMENT_LIMIT");return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(BookingPolicy.SameDoctorDayException.class) ResponseEntity<ProblemDetail> sameDoctorDay(){var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Bạn đã có lịch với bác sĩ này trong ngày đã chọn. Vui lòng chọn ngày khác.");p.setProperty("code","SAME_DOCTOR_SAME_DAY");return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(AppointmentService.SlotConflictException.class) ResponseEntity<ProblemDetail> conflict(){var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Bác sĩ đã có lịch trong khoảng thời gian này.");p.setProperty("code","SLOT_CONFLICT");return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(AppointmentService.PatientOverlapException.class) ResponseEntity<ProblemDetail> patientOverlap(){var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Bạn đã có một lịch khám khác trùng khoảng thời gian này.");p.setProperty("code","PATIENT_TIME_CONFLICT");return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(AppointmentService.HoldExpiredException.class) ResponseEntity<ProblemDetail> holdExpired(){var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Thời gian giữ chỗ đã hết. Vui lòng chọn lại khung giờ.");p.setProperty("code","HOLD_EXPIRED");return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(AppointmentService.ProposalExpiredException.class) ResponseEntity<ProblemDetail> proposalExpired(){var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Đề nghị đặt lịch đã hết hạn. Vui lòng nhắn lễ tân để chọn lại.");p.setProperty("code","PROPOSAL_EXPIRED");return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(SchedulingRecommendationService.SlotUnavailableException.class) ResponseEntity<ProblemDetail> unavailable(SchedulingRecommendationService.SlotUnavailableException e){var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Khung giờ không còn phù hợp với lịch làm việc của bác sĩ.");p.setProperty("code",e.getMessage());return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(ClinicClosureConflict.class) ResponseEntity<ProblemDetail> closureConflict(ClinicClosureConflict e){var time=java.time.format.DateTimeFormatter.ofPattern("HH:mm dd/MM/yyyy").withZone(java.time.ZoneId.of("Asia/Ho_Chi_Minh")).format(e.firstStart);var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Không thể thêm ngày nghỉ vì ngày "+e.date.format(java.time.format.DateTimeFormatter.ofPattern("dd/MM/yyyy"))+" đang có "+e.conflictCount+" lịch hoạt động; lịch sớm nhất lúc "+time+". Vui lòng đổi hoặc hủy các lịch này trước.");p.setProperty("code","CLOSURE_HAS_ACTIVE_APPOINTMENTS");p.setProperty("conflictCount",e.conflictCount);return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(IllegalStateException.class) ResponseEntity<ProblemDetail> state(IllegalStateException e){var p=ProblemDetail.forStatusAndDetail(HttpStatus.CONFLICT,"Không thể chuyển trạng thái lịch khám.");p.setProperty("code",e.getMessage());return ResponseEntity.status(409).body(p);}
 @ExceptionHandler(IllegalArgumentException.class) ResponseEntity<ProblemDetail> bad(IllegalArgumentException e){var p=ProblemDetail.forStatusAndDetail(HttpStatus.BAD_REQUEST,"Yêu cầu lịch khám không hợp lệ.");p.setProperty("code",e.getMessage());return ResponseEntity.badRequest().body(p);}
 @ExceptionHandler(NoSuchElementException.class) ResponseEntity<Void> missing(){return ResponseEntity.notFound().build();}
}
