package com.dermai.appointment;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/appointments") class BookingSupportController{
 private final AppointmentService service;private final AppointmentRepository appointments;private final AppointmentNotificationRepository notifications;private final ClinicClosureRepository closures;private final ReminderActionRepository reminderActions;private final SchedulingRecommendationService scheduling;
 BookingSupportController(AppointmentService service,AppointmentRepository appointments,AppointmentNotificationRepository notifications,ClinicClosureRepository closures,ReminderActionRepository reminderActions,SchedulingRecommendationService scheduling){this.service=service;this.appointments=appointments;this.notifications=notifications;this.closures=closures;this.reminderActions=reminderActions;this.scheduling=scheduling;}
 record Hold(@NotNull UUID patientId,@NotNull UUID doctorId,@NotNull UUID doctorIdentityId,@NotNull Instant startAt,@NotNull Instant endAt){}
 record ConfirmHold(@NotBlank @Size(max=500) String reason){}
 record Proposal(@NotNull UUID patientId,@NotNull UUID patientIdentityId,@NotNull UUID doctorId,@NotNull UUID doctorIdentityId,@NotNull Instant startAt,@NotNull Instant endAt,@NotBlank @Size(max=500) String reason){}
 record Closure(@NotNull LocalDate date,@NotBlank @Size(max=300) String reason){}
 record ReminderBody(@NotBlank @Pattern(regexp="CALLED|RESENT|UNREACHABLE") String action){}
 record ReminderItem(Appointment appointment,ReminderAction latestAction){}
 @PostMapping("/holds") ResponseEntity<Appointment> hold(@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role,@RequestHeader(value="Authorization",required=false) String authorization,@Valid @RequestBody Hold x){require(role,"PATIENT");scheduling.assertAvailable(x.doctorId(),x.startAt(),x.endAt(),null,authorization,role);return ResponseEntity.status(201).body(service.hold(x.patientId(),identity,x.doctorId(),x.doctorIdentityId(),x.startAt(),x.endAt()));}
 @PostMapping("/holds/{id}/confirm") Appointment confirm(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role,@RequestHeader(value="Idempotency-Key",required=false) String key,@Valid @RequestBody ConfirmHold x){require(role,"PATIENT");return service.confirmHold(id,identity,x.reason(),key);}
 @DeleteMapping("/holds/{id}") ResponseEntity<Void> release(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){require(role,"PATIENT");service.releaseHold(id,identity);return ResponseEntity.noContent().build();}
 @PostMapping("/proposals") ResponseEntity<Appointment> propose(@RequestHeader("X-User-Role") String role,@RequestHeader(value="Authorization",required=false) String authorization,@Valid @RequestBody Proposal x){requireAny(role,"RECEPTIONIST","ADMIN");scheduling.assertAvailable(x.doctorId(),x.startAt(),x.endAt(),null,authorization,role);return ResponseEntity.status(201).body(service.propose(x.patientId(),x.patientIdentityId(),x.doctorId(),x.doctorIdentityId(),x.startAt(),x.endAt(),x.reason()));}
 @GetMapping("/proposals/mine") List<Appointment> proposals(@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){require(role,"PATIENT");return appointments.findByPatientIdentityIdOrderByStartAtDesc(identity).stream().filter(x->x.status==AppointmentStatus.PROPOSED&&x.holdExpiresAt!=null&&x.holdExpiresAt.isAfter(Instant.now())).toList();}
 @PostMapping("/proposals/{id}/accept") Appointment acceptProposal(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){require(role,"PATIENT");return service.acceptProposal(id,identity);}
 @PostMapping("/proposals/{id}/decline") Appointment declineProposal(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){require(role,"PATIENT");return service.declineProposal(id,identity);}
 @GetMapping("/notifications/mine") List<AppointmentNotification> mine(@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){require(role,"PATIENT");return notifications.findTop50ByPatientIdentityIdOrderByCreatedAtDesc(identity);}
 @PatchMapping("/notifications/{id}/read") ResponseEntity<Void> read(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID identity,@RequestHeader("X-User-Role") String role){require(role,"PATIENT");var n=notifications.findById(id).orElseThrow(NoSuchElementException::new);if(!identity.equals(n.patientIdentityId))throw new AppointmentController.Forbidden();n.readAt=Instant.now();notifications.save(n);return ResponseEntity.noContent().build();}
 @GetMapping("/closures") List<ClinicClosure> closures(@RequestHeader("X-User-Role") String role){requireAny(role,"ADMIN","RECEPTIONIST","DOCTOR");return closures.findAllByOrderByClosureDateAsc();}
 @PostMapping("/closures") ClinicClosure addClosure(@RequestHeader("X-User-Role") String role,@Valid @RequestBody Closure x){require(role,"ADMIN");var zone=ZoneId.of("Asia/Ho_Chi_Minh");var from=x.date().atStartOfDay(zone).toInstant();var to=x.date().plusDays(1).atStartOfDay(zone).toInstant();if(!appointments.findActiveOverlapping(from,to).isEmpty())throw new IllegalStateException("CLOSURE_HAS_ACTIVE_APPOINTMENTS");return closures.save(new ClinicClosure(x.date(),x.reason()));}
 @DeleteMapping("/closures/{id}") ResponseEntity<Void> deleteClosure(@PathVariable UUID id,@RequestHeader("X-User-Role") String role){require(role,"ADMIN");closures.deleteById(id);return ResponseEntity.noContent().build();}
 @GetMapping("/reminders") List<ReminderItem> reminders(@RequestHeader("X-User-Role") String role){requireAny(role,"RECEPTIONIST","ADMIN");var zone=ZoneId.of("Asia/Ho_Chi_Minh");var from=LocalDate.now(zone).atStartOfDay(zone).toInstant();var to=LocalDate.now(zone).plusDays(2).atStartOfDay(zone).toInstant();return appointments.findByStatusInAndStartAtBetweenOrderByStartAt(EnumSet.of(AppointmentStatus.CONFIRMED),from,to).stream().map(x->new ReminderItem(x,reminderActions.findTopByAppointmentIdOrderByCreatedAtDesc(x.id).orElse(null))).toList();}
 @PostMapping("/{id}/reminder-actions") ReminderAction remind(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID receptionist,@RequestHeader("X-User-Role") String role,@Valid @RequestBody ReminderBody body){requireAny(role,"RECEPTIONIST","ADMIN");var appointment=appointments.findById(id).orElseThrow(NoSuchElementException::new);if(appointment.status!=AppointmentStatus.CONFIRMED)throw new IllegalStateException("REMINDER_REQUIRES_CONFIRMED_APPOINTMENT");var latest=reminderActions.findTopByAppointmentIdOrderByCreatedAtDesc(id);if("RESENT".equals(body.action())&&latest.filter(x->"RESENT".equals(x.actionType)&&x.createdAt.isAfter(Instant.now().minusSeconds(60))).isPresent())return latest.get();var action=reminderActions.save(new ReminderAction(id,receptionist,body.action()));if("RESENT".equals(body.action()))service.notify(appointment,"MANUAL_REMINDER_"+action.id,"Nhắc lịch khám từ lễ tân","Bạn có lịch khám sắp tới. Vui lòng kiểm tra thời gian và đến đúng giờ.");return action;}
 private void require(String got,String role){if(!role.equals(got))throw new AppointmentController.Forbidden();}private void requireAny(String got,String...roles){if(Arrays.stream(roles).noneMatch(got::equals))throw new AppointmentController.Forbidden();}
}
