package com.dermai.appointment;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;import org.springframework.web.server.ResponseStatusException;import java.nio.charset.StandardCharsets;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/appointments/support")
public class SupportController{
 private static final long MAX_IMAGE_BYTES=5L*1024*1024;
 private final SupportMessageRepository messages;private final SlotUpdateBroadcaster updates;private final SupportConversationService conversations;
 SupportController(SupportMessageRepository messages,SlotUpdateBroadcaster updates,SupportConversationService conversations){this.messages=messages;this.updates=updates;this.conversations=conversations;}
 record Send(UUID patientIdentityId,@NotBlank @Size(max=2000) String body){}
 @GetMapping List<SupportMessage> list(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role,@RequestParam(required=false) UUID patientIdentityId){if("PATIENT".equals(role))return messages.findByPatientIdentityIdOrderBySentAtAsc(user);if(!"RECEPTIONIST".equals(role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);if(patientIdentityId!=null){if(!conversations.assignedTo(patientIdentityId,user))throw new ResponseStatusException(HttpStatus.NOT_FOUND);return messages.findByPatientIdentityIdOrderBySentAtAsc(patientIdentityId);}var ids=conversations.list(user,role).stream().filter(item->user.equals(item.assignedReceptionistIdentityId)).map(item->item.patientIdentityId).toList();return ids.isEmpty()?List.of():messages.findByPatientIdentityIdInOrderBySentAtAsc(ids);}
 @GetMapping("/conversations") List<SupportConversation> conversationList(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){if(!Set.of("PATIENT","RECEPTIONIST").contains(role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);return conversations.list(user,role);}
 @PostMapping("/conversations/{patientIdentityId}/claim") SupportConversation claim(@PathVariable UUID patientIdentityId,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){requireReceptionist(role);var result=conversations.claim(patientIdentityId,user);updates.chatChanged();return result;}
 @DeleteMapping("/conversations/{patientIdentityId}/claim") SupportConversation release(@PathVariable UUID patientIdentityId,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){requireReceptionist(role);var result=conversations.release(patientIdentityId,user);updates.chatChanged();return result;}
 @PostMapping("/conversations/{patientIdentityId}/resolve") SupportConversation resolve(@PathVariable UUID patientIdentityId,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){requireReceptionist(role);var result=conversations.resolve(patientIdentityId,user);var x=new SupportMessage();x.id=UUID.randomUUID();x.patientIdentityId=patientIdentityId;x.senderIdentityId=user;x.senderRole="SYSTEM";x.body="Lễ tân đã hoàn tất hỗ trợ. Yêu cầu mới sẽ được Trợ lý Derm tiếp nhận trước.";x.sentAt=Instant.now();messages.save(x);updates.chatChanged();return result;}
 @PostMapping ResponseEntity<SupportMessage> send(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role,@Valid @RequestBody Send body){var patient=resolveSenderPatient(user,role,body.patientIdentityId());var x=newMessage(patient,user,role,body.body().trim());return saved(x,role);}
 @PostMapping(value="/images",consumes=MediaType.MULTIPART_FORM_DATA_VALUE) ResponseEntity<SupportMessage> sendImage(@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Role")String role,@RequestPart(required=false)UUID patientIdentityId,@RequestPart(required=false)String body,@RequestPart("file")MultipartFile file)throws Exception{
  var patient=resolveSenderPatient(user,role,patientIdentityId);
  if(file.isEmpty()||file.getSize()>MAX_IMAGE_BYTES)throw new ResponseStatusException(HttpStatus.PAYLOAD_TOO_LARGE,"Ảnh phải có dung lượng tối đa 5 MB.");
  var bytes=file.getBytes();var contentType=imageContentType(bytes);if(contentType==null)throw new ResponseStatusException(HttpStatus.UNSUPPORTED_MEDIA_TYPE,"Chỉ hỗ trợ ảnh JPG, PNG hoặc WebP.");
  var caption=body==null||body.isBlank()?"Đã gửi một ảnh":body.trim();if(caption.length()>2000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Nội dung tối đa 2000 ký tự.");
  var x=newMessage(patient,user,role,caption);x.attachmentContentType=contentType;x.attachmentOriginalName=safeFilename(file.getOriginalFilename());x.attachmentSizeBytes=(long)bytes.length;x.attachmentData=bytes;return saved(x,role);
 }
 @GetMapping("/{id}/attachment") ResponseEntity<byte[]> attachment(@PathVariable UUID id,@RequestHeader("X-User-Id")UUID user,@RequestHeader("X-User-Role")String role){
  var x=messages.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));
  boolean allowed="PATIENT".equals(role)&&user.equals(x.patientIdentityId)||"RECEPTIONIST".equals(role)&&conversations.assignedTo(x.patientIdentityId,user);
  if(!allowed||x.attachmentData==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND);
  var disposition=ContentDisposition.inline().filename(x.attachmentOriginalName==null?"anh-hoan-tien":x.attachmentOriginalName,StandardCharsets.UTF_8).build();
  return ResponseEntity.ok().cacheControl(CacheControl.noStore()).contentType(MediaType.parseMediaType(x.attachmentContentType)).contentLength(x.attachmentData.length).header(HttpHeaders.CONTENT_DISPOSITION,disposition.toString()).body(x.attachmentData);
 }
 @PatchMapping("/{id}/read") SupportMessage read(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){var x=messages.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));boolean patientMayRead="PATIENT".equals(role)&&user.equals(x.patientIdentityId)&&!"PATIENT".equals(x.senderRole);boolean staffMayRead="RECEPTIONIST".equals(role)&&"PATIENT".equals(x.senderRole)&&conversations.assignedTo(x.patientIdentityId,user);if(!patientMayRead&&!staffMayRead)throw new ResponseStatusException(HttpStatus.FORBIDDEN);x.readAt=Instant.now();var saved=messages.save(x);updates.chatChanged();return saved;}
 private UUID resolveSenderPatient(UUID user,String role,UUID requested){if("PATIENT".equals(role))return user;if("RECEPTIONIST".equals(role)){var patient=Objects.requireNonNull(requested,"patientIdentityId bắt buộc");if(!conversations.assignedTo(patient,user))throw new ResponseStatusException(HttpStatus.CONFLICT,"Bạn cần nhận cuộc trò chuyện trước khi trả lời.");return patient;}throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin chỉ có quyền giám sát hộp thư hỗ trợ.");}
 private SupportMessage newMessage(UUID patient,UUID user,String role,String body){var x=new SupportMessage();x.id=UUID.randomUUID();x.patientIdentityId=patient;x.senderIdentityId=user;x.senderRole=role;x.body=body;x.sentAt=Instant.now();return x;}
 private ResponseEntity<SupportMessage> saved(SupportMessage x,String role){var saved=messages.save(x);if("PATIENT".equals(role))conversations.manualEscalate(x.patientIdentityId);else conversations.touch(x.patientIdentityId);updates.chatChanged();return ResponseEntity.status(201).body(saved);}
 private String imageContentType(byte[] b){if(b.length>=3&&(b[0]&255)==0xff&&(b[1]&255)==0xd8&&(b[2]&255)==0xff)return MediaType.IMAGE_JPEG_VALUE;if(b.length>=8&&(b[0]&255)==0x89&&b[1]==0x50&&b[2]==0x4e&&b[3]==0x47&&b[4]==0x0d&&b[5]==0x0a&&b[6]==0x1a&&b[7]==0x0a)return MediaType.IMAGE_PNG_VALUE;if(b.length>=12&&b[0]=='R'&&b[1]=='I'&&b[2]=='F'&&b[3]=='F'&&b[8]=='W'&&b[9]=='E'&&b[10]=='B'&&b[11]=='P')return "image/webp";return null;}
 private String safeFilename(String value){var name=value==null?"anh-hoan-tien":value.replace('\\','/');name=name.substring(name.lastIndexOf('/')+1).replaceAll("[^\\p{L}\\p{N}._ -]","_").trim();if(name.isBlank())name="anh-hoan-tien";return name.length()>200?name.substring(name.length()-200):name;}
 private void requireReceptionist(String role){if(!"RECEPTIONIST".equals(role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);}
}