package com.dermai.appointment;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/appointments/support")
public class SupportController{
 private final SupportMessageRepository messages;private final SlotUpdateBroadcaster updates;SupportController(SupportMessageRepository messages,SlotUpdateBroadcaster updates){this.messages=messages;this.updates=updates;}
 record Send(UUID patientIdentityId,@NotBlank @Size(max=2000) String body){}
 @GetMapping List<SupportMessage> list(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role,@RequestParam(required=false) UUID patientIdentityId){if("PATIENT".equals(role))return messages.findByPatientIdentityIdOrderBySentAtAsc(user);if(!"RECEPTIONIST".equals(role)&&!"ADMIN".equals(role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);return patientIdentityId==null?messages.findAllByOrderBySentAtAsc():messages.findByPatientIdentityIdOrderBySentAtAsc(patientIdentityId);}
 @PostMapping ResponseEntity<SupportMessage> send(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role,@Valid @RequestBody Send body){UUID patient;if("PATIENT".equals(role))patient=user;else if("RECEPTIONIST".equals(role)||"ADMIN".equals(role)){patient=Objects.requireNonNull(body.patientIdentityId(),"patientIdentityId bắt buộc");}else throw new ResponseStatusException(HttpStatus.FORBIDDEN);var x=new SupportMessage();x.id=UUID.randomUUID();x.patientIdentityId=patient;x.senderIdentityId=user;x.senderRole=role;x.body=body.body().trim();x.sentAt=Instant.now();var saved=messages.save(x);updates.chatChanged();return ResponseEntity.status(201).body(saved);}
 @PatchMapping("/{id}/read") SupportMessage read(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){var x=messages.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));boolean patientMayRead="PATIENT".equals(role)&&user.equals(x.patientIdentityId)&&!"PATIENT".equals(x.senderRole);boolean staffMayRead=("RECEPTIONIST".equals(role)||"ADMIN".equals(role))&&"PATIENT".equals(x.senderRole);if(!patientMayRead&&!staffMayRead)throw new ResponseStatusException(HttpStatus.FORBIDDEN);x.readAt=Instant.now();var saved=messages.save(x);updates.chatChanged();return saved;}
}
