package com.dermai.appointment;
import jakarta.validation.Valid;import jakarta.validation.constraints.*;import org.springframework.http.*;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.time.*;import java.util.*;
@RestController @RequestMapping("/api/v1/appointments/support")
public class SupportController{
 private final SupportMessageRepository messages;private final SlotUpdateBroadcaster updates;private final SupportConversationService conversations;
 SupportController(SupportMessageRepository messages,SlotUpdateBroadcaster updates,SupportConversationService conversations){this.messages=messages;this.updates=updates;this.conversations=conversations;}
 record Send(UUID patientIdentityId,@NotBlank @Size(max=2000) String body){}
 @GetMapping List<SupportMessage> list(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role,@RequestParam(required=false) UUID patientIdentityId){if("PATIENT".equals(role))return messages.findByPatientIdentityIdOrderBySentAtAsc(user);if("ADMIN".equals(role))return patientIdentityId==null?messages.findAllByOrderBySentAtAsc():messages.findByPatientIdentityIdOrderBySentAtAsc(patientIdentityId);if(!"RECEPTIONIST".equals(role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);if(patientIdentityId!=null){if(!conversations.visibleToReceptionist(patientIdentityId,user))throw new ResponseStatusException(HttpStatus.NOT_FOUND);return messages.findByPatientIdentityIdOrderBySentAtAsc(patientIdentityId);}var ids=conversations.list(user,role).stream().map(item->item.patientIdentityId).toList();return ids.isEmpty()?List.of():messages.findByPatientIdentityIdInOrderBySentAtAsc(ids);}
 @GetMapping("/conversations") List<SupportConversation> conversationList(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){return conversations.list(user,role);}
 @PostMapping("/conversations/{patientIdentityId}/claim") SupportConversation claim(@PathVariable UUID patientIdentityId,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){requireReceptionist(role);var result=conversations.claim(patientIdentityId,user);updates.chatChanged();return result;}
 @DeleteMapping("/conversations/{patientIdentityId}/claim") SupportConversation release(@PathVariable UUID patientIdentityId,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){requireReceptionist(role);var result=conversations.release(patientIdentityId,user);updates.chatChanged();return result;}
 @PostMapping("/conversations/{patientIdentityId}/resolve") SupportConversation resolve(@PathVariable UUID patientIdentityId,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){requireReceptionist(role);var result=conversations.resolve(patientIdentityId,user);var x=new SupportMessage();x.id=UUID.randomUUID();x.patientIdentityId=patientIdentityId;x.senderIdentityId=user;x.senderRole="SYSTEM";x.body="Lễ tân đã hoàn tất hỗ trợ. Yêu cầu mới sẽ được Trợ lý Derm tiếp nhận trước.";x.sentAt=Instant.now();messages.save(x);updates.chatChanged();return result;}
 @PostMapping ResponseEntity<SupportMessage> send(@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role,@Valid @RequestBody Send body){UUID patient;if("PATIENT".equals(role))patient=user;else if("RECEPTIONIST".equals(role)){patient=Objects.requireNonNull(body.patientIdentityId(),"patientIdentityId bắt buộc");if(!conversations.assignedTo(patient,user))throw new ResponseStatusException(HttpStatus.CONFLICT,"Bạn cần nhận cuộc trò chuyện trước khi trả lời.");}else throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Admin chỉ có quyền giám sát hộp thư hỗ trợ.");var x=new SupportMessage();x.id=UUID.randomUUID();x.patientIdentityId=patient;x.senderIdentityId=user;x.senderRole=role;x.body=body.body().trim();x.sentAt=Instant.now();var saved=messages.save(x);if("PATIENT".equals(role))conversations.manualEscalate(patient);else conversations.touch(patient);updates.chatChanged();return ResponseEntity.status(201).body(saved);}
 @PatchMapping("/{id}/read") SupportMessage read(@PathVariable UUID id,@RequestHeader("X-User-Id") UUID user,@RequestHeader("X-User-Role") String role){var x=messages.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));boolean patientMayRead="PATIENT".equals(role)&&user.equals(x.patientIdentityId)&&!"PATIENT".equals(x.senderRole);boolean staffMayRead="RECEPTIONIST".equals(role)&&"PATIENT".equals(x.senderRole)&&conversations.assignedTo(x.patientIdentityId,user);if(!patientMayRead&&!staffMayRead)throw new ResponseStatusException(HttpStatus.FORBIDDEN);x.readAt=Instant.now();var saved=messages.save(x);updates.chatChanged();return saved;}
 private void requireReceptionist(String role){if(!"RECEPTIONIST".equals(role))throw new ResponseStatusException(HttpStatus.FORBIDDEN);}
}
